CREATE DATABASE ALURA;

USE ALURA;

CREATE TABLE DADOS_CURSO(
	REGISTER_ID INT NOT NULL AUTO_INCREMENT, # ID INTERNO PARA CONTROLE INTERNO DA TABELA
	TITULO_CURSO VARCHAR(100) NULL,
	PROFESSOR_CURSO VARCHAR(100) NULL,
    CARGA_HORARIA_CURSO VARCHAR(10) NULL,
    DESCRICAO_CURSO VARCHAR(400) NULL,
	PRIMARY KEY (REGISTER_ID)
);